### PR TITLE
Android App: task execution, aborting tasks, sending task_events, test runner

### LINKED ISSUE #34: Implement Arm functionality in the backend/drone sdks

### LINKED ISSUE #35: Add functionality to abort a mission for a drone
This will allow the drone to be sent on another mission, or used as an available drone in a proposed mission

### LINKED ISSUE #36: With a successful connection all specifications should be sent to the backend

### LINKED ISSUE #38: Investigate and fix drone disconnect crash in android app
Android app readme, under "Connecting to the product": 
```Currently, there is a bug somewhere that causes the app to crash when the drone is disconnected```

### LINKED ISSUE #51: Implement getter functions for DJI adapter
Implement the 'getter' definitions for interface functions for the DJI communication. The getters are the functions for getting information from the drone, such as the battery level, telemetry etc.

### LINKED ISSUE #56: messageHandler for Android app
Class called messageHandler that has methods for all messages that gets sent from app to backend.
sends: task complete, task failed + error, task aborted, registration data, telemetry

### LINKED ISSUE #69: Create tests for DJI drone commands in the android app
Create a new activity with a list of rows. Each row has buttons, text fields (for lon & lat etc) and a "Run" button. The submit button runs a test for a specific command, such as flying to a point, playing a sound etc.

### PR DESCRIPTION
**Pull request by isaclilja**
### Description
- Created methods for executing all necessary tasks (go_to, speaker, led, beacon, spotlight, angle_camera) in DJIFlightManager
- Created methods for aborting tasks, either specified tasks or all in DJIFlightManager
- Automatically retrieving capabilities from the drone and sending them to backend when a drone/backend connects in WebsocketClientHandler
- Sending task_events when a task suceeds, fails or is aborted through MessageHandler
- Added the ability to run tests through adding them in TaskTestRunner and selecting them in the dropdown in the apps GUI
- Added logging filters in drone_communication
- Added DroneAdapter selection in DroneAdapterManager and WebsocketClientHandler
- Added method to get CameraResolution for specific DJI model in DJIDroneSpecs
- Added additional tasks in the mock mission (all possible tasks) and tested all of them successfully
- Added automatic landing confirmation

### Linked issue
Closes #69 
Closes #56 
Closes #51 
Closes #36 
Closes #35 
Closes #34 
Closes #38 

### Checklist
- [x] Added/Updated tests
- [x] Tests passed
- [x] Updated code or repo documentation
- [x] Linked an issue
- [x] Have reviewed my code (code and files follows naming conventions)

### CODE REVIEW

File: android-app/app/src/main/java/com/dji/sdk/sample/MainActivity.java [hunk 1]
```diff
@@ -103,11 +103,11 @@ protected void onCreate(Bundle savedInstanceState) {
 
     }
 
-    @Override
-    protected void onDestroy() {
-        super.onDestroy();
-        AutoConnectManager.getInstance(getApplicationContext()).stop();
-    }
+    // @Override
```
Comment (lud99) [inline android-app/app/src/main/java/com/dji/sdk/sample/MainActivity.java]: Why is this code commented out?
Remove the code if not needed

File: android-app/app/src/main/java/com/dji/sdk/sample/SecondFragment.java [hunk 2]
```diff
@@ -166,10 +163,10 @@ public void onClick(View v) {
             public void onClick(View v) {
                 if(getStatus().equals(MissionState.READY_TO_UPLOAD) && !flightmanager.getState().isFlying()){
                     //startMonitoring();
-                    flightmanager.onArm();
+                    //flightmanager.onArm();
```
Comment (lud99) [inline android-app/app/src/main/java/com/dji/sdk/sample/SecondFragment.java]: Why commented out?
remove the code if not used

File: android-app/app/src/main/java/com/dji/sdk/sample/TaskTestRunner.java [hunk 3]
```diff
@@ -0,0 +1,250 @@
...
+            @Override
+            public void onFailure(String reason) {
+                Log.w(TAG, "Registration data unavailable; SEND_REGISTRATION_DATA skipped. Reason: " + reason);
+            }
+        });
+    }
+
+    private void logRegistrationDataPayload(String missionId, int taskIndex, DroneAdapter.RegistrationData registrationData) {
+        if (registrationData == null) {
+            Log.w(TAG, "Registration data unavailable; SEND_REGISTRATION_DATA skipped.");
```
Comment (lud99) [inline android-app/app/src/main/java/com/dji/sdk/sample/TaskTestRunner.java]: Log.e instead? this does seem like an error

File: android-app/app/src/main/java/com/dji/sdk/sample/TaskTestRunner.java [hunk 4]
```diff
@@ -0,0 +1,250 @@
...
+    }
+
+    public void runLand(String missionId, int taskIndex) {
+        adapter.land(missionId, taskIndex);
+    }
+
+    public void runSendTelemetry(String missionId, int taskIndex) {
+        DroneAdapter.Telemetry telemetry = adapter.getTelemetry();
+        if (telemetry == null) {
+            Log.w(TAG, "Telemetry unavailable; SEND_TELEMETRY skipped.");
```
Comment (lud99) [inline android-app/app/src/main/java/com/dji/sdk/sample/TaskTestRunner.java]: Log.e instead? this does seem like an error

File: android-app/app/src/main/java/com/dji/sdk/sample/WebsocketClientHandler.java [hunk 5]
```diff
@@ -283,14 +362,261 @@ private synchronized void startPositionSending() {
             wsPositionHandlerThread = new HandlerThread("WebSocketPositionSender");
             wsPositionHandlerThread.start();
```
Comment (lud99) [inline android-app/app/src/main/java/com/dji/sdk/sample/WebsocketClientHandler.java:363]: Have you checked so it doesn't send duplicate telemetry messages?

File: android-app/app/src/main/java/com/dji/sdk/sample/WebsocketClientHandler.java [hunk 6]
```diff
@@ -283,14 +362,261 @@ private synchronized void startPositionSending() {
...
+            missionId = "unknown";
+        }
+        return missionId;
+    }
+
+    private int readTaskIndex(JSONObject jsonMessage) {
+        if (jsonMessage.has("index")) {
+            return jsonMessage.optInt("index", -1);
+        }
+        if (jsonMessage.has("task_index")) {
```
Comment (lud99) [inline android-app/app/src/main/java/com/dji/sdk/sample/WebsocketClientHandler.java:609]: "taskIndex" should not be a property anywhere, right?

File: android-app/app/src/main/java/com/dji/sdk/sample/WebsocketClientHandler.java [hunk 7]
```diff
@@ -283,14 +362,261 @@ private synchronized void startPositionSending() {
...
+            default:
+                Log.w(TAG, "Unsupported task action: " + action);
+                break;
+        }
+    }
+
+    private String readMissionId(JSONObject jsonMessage) {
+        String missionId = jsonMessage.optString("mission_id", "");
+        if (missionId.isEmpty()) {
+            missionId = jsonMessage.optString("missionID", "");
```
Comment (lud99) [inline android-app/app/src/main/java/com/dji/sdk/sample/WebsocketClientHandler.java]: "missionID" should not be a property anywhere, right?

File: android-app/app/src/main/java/com/dji/sdk/sample/WebsocketClientHandler.java [hunk 8]
```diff
@@ -335,7 +661,7 @@ public void run() {
         try {
             String ping = "{\"msg_type\": \"ping\"}";
             webSocketClient.send(ping);
-            Log.d(TAG, "Heartbeat ping sent");
+            // Log.d(TAG, "Heartbeat ping sent");
```
Comment (lud99) [inline android-app/app/src/main/java/com/dji/sdk/sample/WebsocketClientHandler.java]: remove the line

File: android-app/app/src/main/java/com/dji/sdk/sample/WSPosition.java [hunk 9]
```diff
@@ -30,60 +24,33 @@ public void run() {
         // TODO Check that it is connected
```
Comment (lud99) [inline android-app/app/src/main/java/com/dji/sdk/sample/WSPosition.java]: remove the TODO, as i assume that it is fixed

File: android-app/app/src/main/res/RESULTS.txt [hunk 10]
```diff
@@ -0,0 +1,37 @@
+--SEND_TELEMETRY--
+Before GO_TO: {"msg_type":"Telemetry","mission_id":"test-mission","task_index":2,"droneID":"unknown","lat":22.542812999999995,"lon":113.95890200000001,"alt":0,"heading":0,"speed":0,"batteryPercent":86}
+After GO_TO: {"msg_type":"Telemetry","mission_id":"test-mission","task_index":10,"droneID":"unknown","lat":22.54282261668693,"lon":113.95891184599402,"alt":9.899999618530273,"heading":0,"speed":0,"batteryPercent":80}
```
Comment (lud99) [inline android-app/app/src/main/res/RESULTS.txt]: why is it droneID and not drone_id?

File: android-app/app/src/main/res/RESULTS.txt [hunk 11]
```diff
@@ -0,0 +1,37 @@
...
+--GO_TO--
+Åkte upp till 10m. Åkte till ny possition. Stannade där. 
+När jag kör det igen får jag:
+- Load waypoint filed in stage config Waypoint count is invalid
+- Mission upload failed: Null Mission retrying...
+- Mission start: The information of mission is invalid
+Nu funkar det. Kan även åka på nytt mission.
+
+--GO_HOME--
+Påbörjade landning. Landade på nuvarande koordinater. Stannade på 0.4m. Inte lagrat home?
```
Comment (lud99) [inline android-app/app/src/main/res/RESULTS.txt]: Löste du detta med att den inte går helt hem?

File: android-app/app/src/main/res/RESULTS.txt [hunk 12]
```diff
@@ -0,0 +1,37 @@
+--SEND_TELEMETRY--
+Before GO_TO: {"msg_type":"Telemetry","mission_id":"test-mission","task_index":2,"droneID":"unknown","lat":22.542812999999995,"lon":113.95890200000001,"alt":0,"heading":0,"speed":0,"batteryPercent":86}
+After GO_TO: {"msg_type":"Telemetry","mission_id":"test-mission","task_index":10,"droneID":"unknown","lat":22.54282261668693,"lon":113.95891184599402,"alt":9.899999618530273,"heading":0,"speed":0,"batteryPercent":80}
+After GO_HOME: {"msg_type":"Telemetry","mission_id":"test-mission","task_index":22,"droneID":"unknown","lat":22.542822616543432,"lon":113.9589118459581,"alt":0.4000000059604645,"heading":0,"speed":0,"batteryPercent":75}
+SUCCESS 
+
+{"msg_type":"Telemetry","mission_id":"test-mission","task_index":3,"droneID":"2763KAH0H1X35H","lat":22.542812999999995,"lon":113.95890200000001,"alt":0,"heading":0,"speed":0,"batteryPercent":62}
+{"msg_type":"Telemetry","mission_id":"test-mission","task_index":5,"droneID":"2763KAH0H1X35H","lat":22.54381107055367,"lon":113.95990002593139,"alt":30,"heading":0,"speed":0,"batteryPercent":58}
```
Comment (lud99) [inline android-app/app/src/main/res/RESULTS.txt]: Borde vara "telemetry"?

File: android-app/app/build.gradle [hunk 13]
```diff
@@ -9,7 +9,7 @@ android {
     defaultConfig {
         applicationId "com.dji.sdk.sample"
         minSdk 24
-        targetSdk 33
+        targetSdk 30 // Tried changing from 33 to 30
```
Comment (lud99) [inline android-app/app/build.gradle]: Varför funkade det att nedgradera SDKn?
Skriv isåfall mer förklarande kommentar varför för nästa år :=)

File: communication_software/communication_software/drone_communication.py
Comment (lud99) [inline communication_software/communication_software/drone_communication.py:1]: Good!
To keep the tests, create some global variable called "doMockMission" and only send the mock mission if it is sent

File: communication_software/communication_software/drone_communication.py [hunk 14]
```diff
@@ -303,7 +324,12 @@ async def webs_server(self, ws: WebSocketServerProtocol) -> None:
         try:
             while True:
                 data = await ws.recv()
-                print(f"Received from {connection_id}: {data}")
+                filter_types = ["answer", "candidate", "ping", "telemetry"] # Enter keywords to filter out from logs
```
Comment (lud99) [inline communication_software/communication_software/drone_communication.py]: Why is this needed? arent all rtc messages be parsed successfully?

File: communication_software/fix.txt [hunk 15]
```diff
@@ -0,0 +1,35 @@
...
+        "camera":{"aspect_ratio":1.7777778, "horizontal_fov":72.4, "resolution_height":1512, "resolution_width":2688},
+        "led":{"types":["beacon", "rear", "front"]},
+        "spotlight":false,
+        "speaker":{"audio_files":[ "alarm" ]}
+        }
+} 
+
+    5 validation errors for tagged-union[
+    TaskMessage,
+    DroneRegistrationMessage,
```
Comment (lud99) [inline communication_software/fix.txt]: Are these issues fixed? if so remove the file

**Review by lud99 — CHANGES_REQUESTED** [review]

**Comment by lud99** [comment]
Och har du löst denna? denna var för att om den tappar anslutningen till backend, inte kontrollern eller så.
https://github.com/lud99/drone-project-psu-chalmers/issues/41

**Comment by lud99** [comment]
förlåt :D men råkar du veta om denna buggen går att återskapa? https://github.com/lud99/drone-project-psu-chalmers/issues/38

File: communication_software/communication_software/drone_communication.py (hunk 14 above)
Comment (isaclilja) [reply communication_software/communication_software/drone_communication.py]: Det var främst för att inte få alla pings och telemetri i flödet så man enklare kunde se det man ville kolla på

**Comment by isaclilja** [comment]
> Och har du löst denna? denna var för att om den tappar anslutningen till backend, inte kontrollern eller så. #41

Nej det har jag inte. Tar bort den

> förlåt :D men råkar du veta om denna buggen går att återskapa? #38

Nej. Jag har testat väldigt mycket utan att få den buggen

File: communication_software/communication_software/drone_communication.py
Comment (isaclilja) [reply communication_software/communication_software/drone_communication.py:1]: La till det i env. med default false

File: android-app/app/src/main/java/com/dji/sdk/sample/WebsocketClientHandler.java (hunk 5 above)
Comment (isaclilja) [reply android-app/app/src/main/java/com/dji/sdk/sample/WebsocketClientHandler.java:363]: Yes, 1 per sekund

**Review by lud99 — APPROVED** [review]
